name: bactopia-phyloflash
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.2.3
  - bbmap=38.87
  - bedtools=2.29.2
  - binutils_impl_linux-64=2.35.1
  - binutils_linux-64=2.35
  - biopython=1.76
  - bowtie=1.2.3
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - certifi=2019.11.28
  - curl=7.71.1
  - emirge=0.61.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.5.0
  - gfortran_linux-64=7.5.0
  - giflib=5.2.1
  - glib=2.66.3
  - graphite2=1.3.13
  - gsl=2.6
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - harfbuzz=2.7.2
  - htslib=1.11
  - icu=67.1
  - iqtree=2.0.3
  - jpeg=9d
  - kernel-headers_linux-64=2.6.32
  - krb5=1.17.2
  - lcms2=2.11
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libdeflate=1.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.66.3
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - llvm-meta=7.0.0
  - lz4-c=1.9.3
  - mafft=7.475
  - make=4.3
  - ncurses=6.2
  - numpy=1.16.5
  - openjdk=11.0.8
  - openmp=7.0.0
  - openssl=1.1.1i
  - pango=1.42.4
  - pbzip2=1.1.13
  - pcre=8.44
  - pcre2=10.35
  - perl=5.32.0
  - phyloflash=3.4
  - pigz=2.3.4
  - pip=20.1.1
  - pixman=0.40.0
  - pthread-stubs=0.4
  - pysam=0.16.0.1
  - python=2.7.15
  - python_abi=2.7
  - r-assertthat=0.2.1
  - r-backports=1.2.1
  - r-base=4.0.2
  - r-brio=1.1.1
  - r-callr=3.5.1
  - r-cli=2.2.0
  - r-colorspace=2.0_0
  - r-crayon=1.3.4
  - r-desc=1.2.0
  - r-diffobj=0.3.3
  - r-digest=0.6.27
  - r-ellipsis=0.3.1
  - r-evaluate=0.14
  - r-fansi=0.4.2
  - r-farver=2.0.3
  - r-getopt=1.20.3
  - r-ggdendro=0.1.22
  - r-ggplot2=3.3.3
  - r-glue=1.4.2
  - r-gtable=0.3.0
  - r-isoband=0.2.3
  - r-jsonlite=1.7.2
  - r-labeling=0.4.2
  - r-lattice=0.20_41
  - r-lifecycle=0.2.0
  - r-magrittr=2.0.1
  - r-mass=7.3_53
  - r-matrix=1.3_2
  - r-mgcv=1.8_33
  - r-munsell=0.5.0
  - r-nlme=3.1_150
  - r-optparse=1.6.6
  - r-pillar=1.4.7
  - r-pkgbuild=1.2.0
  - r-pkgconfig=2.0.3
  - r-pkgload=1.1.0
  - r-plyr=1.8.6
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.4.5
  - r-ps=1.5.0
  - r-r6=2.5.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.6
  - r-rematch2=2.1.2
  - r-reshape2=1.4.4
  - r-rlang=0.4.10
  - r-rprojroot=2.0.2
  - r-rstudioapi=0.13
  - r-scales=1.1.1
  - r-stringi=1.5.3
  - r-stringr=1.4.0
  - r-testthat=3.0.1
  - r-tibble=3.0.5
  - r-utf8=1.1.4
  - r-vctrs=0.3.6
  - r-viridislite=0.3.0
  - r-waldo=0.2.3
  - r-withr=2.4.0
  - r-zeallot=0.1.0
  - readline=8.0
  - samtools=1.11
  - scipy=1.2.1
  - sed=4.8
  - setuptools=44.0.0
  - spades=3.14.1
  - sqlite=3.34.0
  - sysroot_linux-64=2.12
  - tbb=2020.2
  - tk=8.6.10
  - tktable=2.10
  - vsearch=2.15.1
  - wheel=0.36.2
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.8
