name: bactopia-roary
version: 1.4.x
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.1.5
  - appdirs=1.4.3
  - aragorn=1.2.38
  - barrnap=0.9
  - bcbio-gff=0.6.6
  - bedtools=2.29.2
  - binutils_impl_linux-64=2.33.1
  - binutils_linux-64=2.33.1
  - biopython=1.76
  - blast=2.9.0
  - bwidget=1.9.14
  - bx-python=0.8.8
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cairo=1.16.0
  - cd-hit=4.8.1
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - clonalframeml=1.12
  - clustalw=2.1
  - cryptography=2.8
  - curl=7.68.0
  - dbus=1.13.6
  - entrez-direct=13.3
  - enum34=1.1.9
  - ete3=3.1.1
  - expat=2.2.9
  - fasttree=2.1.10
  - fontconfig=2.13.1
  - freetype=2.10.0
  - fribidi=1.0.5
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - giflib=5.2.1
  - glib=2.58.3
  - graphite2=1.3.13
  - graphviz=2.42.3
  - gsl=2.6
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=2.4.0
  - hmmer=3.3
  - icu=64.2
  - idna=2.9
  - infernal=1.1.2
  - iqtree=1.6.12
  - jpeg=9c
  - krb5=1.16.4
  - lcms2=2.9
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.68.0
  - libdb=6.1.26
  - libedit=3.1.20170329
  - libfaketime=0.9.8
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgd=2.2.5
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - libiconv=1.15
  - libidn11=1.34
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.8
  - libpng=1.6.37
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp=1.0.2
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvm-openmp=9.0.1
  - lxml=4.5.0
  - lz4-c=1.8.3
  - lzo=2.10
  - mafft=7.455
  - make=4.2.1
  - maskrc-svg=0.5
  - mcl=14.137
  - minced=0.4.2
  - ncbi-genome-download=0.2.12
  - ncurses=6.1
  - nspr=4.25
  - nss=3.47
  - numpy=1.18.1
  - openjdk=11.0.1
  - openssl=1.1.1d
  - paml=4.9
  - pango=1.42.4
  - parallel=20200122
  - pcre=8.44
  - perl=5.26.2
  - perl-aceperl=1.92
  - perl-algorithm-diff=1.1903
  - perl-algorithm-munkres=0.08
  - perl-apache-test=1.40
  - perl-app-cpanminus=1.7044
  - perl-appconfig=1.71
  - perl-archive-tar=2.32
  - perl-array-compare=3.0.1
  - perl-array-utils=0.5
  - perl-autoloader=5.74
  - perl-base=2.23
  - perl-bio-asn1-entrezgene=1.73
  - perl-bio-coordinate=1.007001
  - perl-bio-featureio=1.6.905
  - perl-bio-phylo=0.58
  - perl-bio-samtools=1.43
  - perl-bio-tools-phylo-paml=1.7.3
  - perl-bio-tools-run-alignment-clustalw=1.7.4
  - perl-bio-tools-run-alignment-tcoffee=1.7.4
  - perl-bioperl=1.7.2
  - perl-bioperl-core=1.007002
  - perl-bioperl-run=1.007002
  - perl-business-isbn=3.004
  - perl-business-isbn-data=20140910.003
  - perl-cache-cache=1.08
  - perl-capture-tiny=0.48
  - perl-carp=1.38
  - perl-cgi=4.44
  - perl-class-data-inheritable=0.08
  - perl-class-inspector=1.34
  - perl-class-load=0.25
  - perl-class-load-xs=0.10
  - perl-class-method-modifiers=2.12
  - perl-clone=0.42
  - perl-common-sense=3.74
  - perl-compress-raw-bzip2=2.087
  - perl-compress-raw-zlib=2.087
  - perl-constant=1.33
  - perl-convert-binary-c=0.78
  - perl-convert-binhex=1.125
  - perl-crypt-rc4=2.02
  - perl-data-dumper=2.173
  - perl-data-optlist=0.110
  - perl-data-stag=0.14
  - perl-date-format=2.30
  - perl-db-file=1.852
  - perl-dbd-sqlite=1.64
  - perl-dbi=1.642
  - perl-devel-globaldestruction=0.14
  - perl-devel-overloadinfo=0.005
  - perl-devel-stacktrace=2.04
  - perl-digest-hmac=1.03
  - perl-digest-md5=2.55
  - perl-digest-md5-file=0.08
  - perl-digest-perl-md5=1.9
  - perl-digest-sha1=2.13
  - perl-dist-checkconflicts=0.11
  - perl-dynaloader=1.25
  - perl-email-date-format=1.005
  - perl-encode=2.88
  - perl-encode-locale=1.05
  - perl-error=0.17027
  - perl-eval-closure=0.14
  - perl-exception-class=1.44
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002001
  - perl-extutils-makemaker=7.36
  - perl-file-find-rule=0.34
  - perl-file-grep=0.02
  - perl-file-listing=6.04
  - perl-file-path=2.16
  - perl-file-slurp-tiny=0.004
  - perl-file-slurper=0.012
  - perl-file-sort=1.01
  - perl-file-temp=0.2304
  - perl-file-which=1.23
  - perl-font-afm=1.20
  - perl-font-ttf=1.06
  - perl-gd=2.71
  - perl-getopt-long=2.50
  - perl-graph=0.9704
  - perl-graph-readwrite=2.09
  - perl-graphviz=2.24
  - perl-html-element-extended=1.18
  - perl-html-entities-numbered=0.04
  - perl-html-formatter=2.16
  - perl-html-parser=3.72
  - perl-html-tableextract=2.13
  - perl-html-tagset=3.20
  - perl-html-tidy=1.60
  - perl-html-tree=5.07
  - perl-html-treebuilder-xpath=0.14
  - perl-http-cookies=6.04
  - perl-http-daemon=6.01
  - perl-http-date=6.02
  - perl-http-message=6.18
  - perl-http-negotiate=6.01
  - perl-image-info=1.38
  - perl-image-size=3.300
  - perl-io-compress=2.087
  - perl-io-html=1.001
  - perl-io-sessiondata=1.03
  - perl-io-socket-ssl=2.066
  - perl-io-string=1.08
  - perl-io-stringy=2.111
  - perl-io-tty=1.12
  - perl-io-zlib=1.10
  - perl-ipc-run=20180523.0
  - perl-ipc-sharelite=0.17
  - perl-jcode=2.07
  - perl-json=4.02
  - perl-json-xs=2.34
  - perl-lib=0.63
  - perl-libwww-perl=6.39
  - perl-libxml-perl=0.08
  - perl-list-moreutils=0.428
  - perl-list-moreutils-xs=0.428
  - perl-log-log4perl=1.49
  - perl-lwp-mediatypes=6.04
  - perl-lwp-protocol-https=6.07
  - perl-lwp-simple=6.15
  - perl-mailtools=2.21
  - perl-math-cdf=0.1
  - perl-math-derivative=1.01
  - perl-math-random=0.72
  - perl-math-spline=0.02
  - perl-mime-base64=3.15
  - perl-mime-lite=3.030
  - perl-mime-tools=5.508
  - perl-mime-types=2.17
  - perl-mldbm=2.05
  - perl-module-implementation=0.09
  - perl-module-runtime=0.016
  - perl-module-runtime-conflicts=0.003
  - perl-moo=2.003004
  - perl-moose=2.2011
  - perl-mozilla-ca=20180117
  - perl-mro-compat=0.13
  - perl-net-http=6.19
  - perl-net-ssleay=1.88
  - perl-ntlm=1.09
  - perl-number-compare=0.03
  - perl-ole-storage_lite=0.19
  - perl-package-deprecationmanager=0.17
  - perl-package-stash=0.38
  - perl-package-stash-xs=0.28
  - perl-params-util=1.07
  - perl-parent=0.236
  - perl-parse-recdescent=1.967015
  - perl-parse-yapp=1.21
  - perl-pathtools=3.75
  - perl-pdf-api2=2.035
  - perl-perlio-utf8_strict=0.007
  - perl-pod-escapes=1.07
  - perl-pod-usage=1.69
  - perl-postscript=0.06
  - perl-role-tiny=2.000008
  - perl-scalar-list-utils=1.52
  - perl-set-scalar=1.29
  - perl-soap-lite=1.19
  - perl-socket=2.027
  - perl-sort-naturally=1.03
  - perl-spreadsheet-parseexcel=0.65
  - perl-spreadsheet-writeexcel=2.40
  - perl-statistics-descriptive=3.0702
  - perl-storable=3.15
  - perl-sub-exporter=0.987
  - perl-sub-exporter-progressive=0.001013
  - perl-sub-identify=0.14
  - perl-sub-install=0.928
  - perl-sub-name=0.21
  - perl-sub-quote=2.006003
  - perl-sub-uplevel=0.2800
  - perl-svg=2.84
  - perl-svg-graph=0.02
  - perl-task-weaken=1.06
  - perl-template-toolkit=2.26
  - perl-test=1.26
  - perl-test-deep=1.128
  - perl-test-differences=0.67
  - perl-test-exception=0.43
  - perl-test-harness=3.42
  - perl-test-leaktrace=0.16
  - perl-test-most=0.35
  - perl-test-requiresinternet=0.05
  - perl-test-warn=0.36
  - perl-text-csv=2.00
  - perl-text-diff=1.45
  - perl-text-glob=0.11
  - perl-tie-ixhash=1.23
  - perl-time-hires=1.9760
  - perl-time-local=1.28
  - perl-timedate=2.30
  - perl-tree-dag_node=1.31
  - perl-try-tiny=0.30
  - perl-type-tiny=1.004004
  - perl-types-serialiser=1.0
  - perl-unicode-map=0.112
  - perl-uri=1.76
  - perl-www-robotrules=6.02
  - perl-xml-dom=1.46
  - perl-xml-dom-xpath=0.14
  - perl-xml-filter-buffertext=1.01
  - perl-xml-libxml=2.0132
  - perl-xml-libxslt=1.94
  - perl-xml-namespacesupport=1.12
  - perl-xml-parser=2.44
  - perl-xml-regexp=0.04
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - perl-xml-sax-expat=0.51
  - perl-xml-sax-writer=0.57
  - perl-xml-simple=2.25
  - perl-xml-twig=3.52
  - perl-xml-writer=0.625
  - perl-xml-xpath=1.44
  - perl-xml-xpathengine=0.14
  - perl-xsloader=0.24
  - perl-yaml=1.29
  - pigz=2.3.4
  - pip=20.0.2
  - pixman=0.38.0
  - prank=v.170427
  - prodigal=2.6.3
  - prokka=1.14.6
  - pthread-stubs=0.4
  - pycparser=2.19
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.12.3
  - pysocks=1.7.1
  - python=3.7.6
  - python-lzo=1.12
  - qt=5.12.5
  - r-assertthat=0.2.1
  - r-base=3.6.2
  - r-cli=1.1.0
  - r-colorspace=1.4
  - r-crayon=1.3.4
  - r-dichromat=2.0
  - r-digest=0.6.18
  - r-fansi=0.4.0
  - r-ggplot2=3.1.1
  - r-glue=1.3.1
  - r-gtable=0.3.0
  - r-labeling=0.3
  - r-lattice=0.20
  - r-lazyeval=0.2.2
  - r-magrittr=1.5
  - r-mass=7.3
  - r-matrix=1.2
  - r-mgcv=1.8
  - r-munsell=0.5.0
  - r-nlme=3.1
  - r-pillar=1.3.1
  - r-pkgconfig=2.0.2
  - r-plyr=1.8.4
  - r-r6=2.4.0
  - r-rcolorbrewer=1.1
  - r-rcpp=1.0.1
  - r-reshape2=1.4.3
  - r-rlang=0.3.4
  - r-scales=1.0.0
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-tibble=2.1.1
  - r-utf8=1.1.4
  - r-viridislite=0.3.0
  - r-withr=2.1.2
  - readline=8.0
  - rename=1.601
  - requests=2.23.0
  - roary=3.13.0
  - scipy=1.4.1
  - sed=4.7
  - setuptools=45.2.0
  - six=1.14.0
  - snp-dists=0.6.3
  - sqlite=3.30.1
  - svgwrite=1.3.1
  - t_coffee=11.0.8
  - tbl2asn-forever=25.7.1f
  - tidyp=1.04
  - tk=8.6.10
  - tktable=2.10
  - urllib3=1.25.7
  - wheel=0.34.2
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
