name: bactopia-ismapper
version: 1.4.x
channels:
  - rpetit3
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bedtools=2.27.1
  - biopython=1.76
  - blast=2.9.0
  - bwa=0.7.17
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - curl=7.68.0
  - entrez-direct=13.3
  - expat=2.2.9
  - htslib=1.10.2
  - ismapper=2.0.2
  - krb5=1.16.4
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.68.0
  - libdeflate=1.3
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - liblapack=3.8.0
  - libopenblas=0.3.8
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - llvm-openmp=9.0.1
  - ncurses=6.1
  - numpy=1.18.1
  - openssl=1.1.1d
  - pcre=8.44
  - perl=5.26.2
  - perl-app-cpanminus=1.7044
  - perl-archive-tar=2.32
  - perl-base=2.23
  - perl-business-isbn=3.004
  - perl-business-isbn-data=20140910.003
  - perl-carp=1.38
  - perl-common-sense=3.74
  - perl-compress-raw-bzip2=2.087
  - perl-compress-raw-zlib=2.087
  - perl-constant=1.33
  - perl-data-dumper=2.173
  - perl-digest-hmac=1.03
  - perl-digest-md5=2.55
  - perl-encode=2.88
  - perl-encode-locale=1.05
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002001
  - perl-extutils-makemaker=7.36
  - perl-file-listing=6.04
  - perl-file-path=2.16
  - perl-file-temp=0.2304
  - perl-html-parser=3.72
  - perl-html-tagset=3.20
  - perl-html-tree=5.07
  - perl-http-cookies=6.04
  - perl-http-daemon=6.01
  - perl-http-date=6.02
  - perl-http-message=6.18
  - perl-http-negotiate=6.01
  - perl-io-compress=2.087
  - perl-io-html=1.001
  - perl-io-socket-ssl=2.066
  - perl-io-zlib=1.10
  - perl-json=4.02
  - perl-json-xs=2.34
  - perl-libwww-perl=6.39
  - perl-list-moreutils=0.428
  - perl-list-moreutils-xs=0.428
  - perl-lwp-mediatypes=6.04
  - perl-lwp-protocol-https=6.07
  - perl-mime-base64=3.15
  - perl-mozilla-ca=20180117
  - perl-net-http=6.19
  - perl-net-ssleay=1.88
  - perl-ntlm=1.09
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.52
  - perl-socket=2.027
  - perl-storable=3.15
  - perl-test-requiresinternet=0.05
  - perl-time-local=1.28
  - perl-try-tiny=0.30
  - perl-types-serialiser=1.0
  - perl-uri=1.76
  - perl-www-robotrules=6.02
  - perl-xml-namespacesupport=1.12
  - perl-xml-parser=2.44
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - perl-xml-sax-expat=0.51
  - perl-xml-simple=2.25
  - perl-xsloader=0.24
  - pip=20.0.2
  - python=3.7.6
  - readline=8.0
  - samtools=1.10
  - setuptools=45.2.0
  - sqlite=3.30.1
  - tk=8.6.10
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
