name: test-conda-envs
on:
  schedule:
    # At 04:30 on Sunday, Tuesday, and Thursday
    - cron:  '30 4 * * 0,2,4'

jobs:
  test-conda-envs:          
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout bactopia/bactopia
        uses: actions/checkout@v2

      - name: Free up Disk Space
        run: bash ${GITHUB_WORKSPACE}/bin/gh-actions/free-disk-space.sh

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: bactopia
          auto-activate-base: false

      - name: Setup Bactopia Environment
        run: bash ${GITHUB_WORKSPACE}/bin/gh-actions/setup-bactopia-env.sh ${CONDA} ${GITHUB_WORKSPACE} 1

      - name: Environment Information
        run: uname -a && env

      - name: Build Bactopia Environment
        run: conda create -n bactopia-bioconda -y -c conda-forge -c bioconda bactopia

      - name: Build Bactopia Process and Tool Environments
        run: bactopia build ${GITHUB_WORKSPACE}/conda ${GITHUB_WORKSPACE}/envs --include_tools --verbose

      - name: List Conda Environments
        run: conda env list

      - name: Test Commands
        run: |
          VERSION=`${BACTOPIA}/bin/bactopia version | cut -d " " -f 2`
          BACTOPIA_VERSION="${VERSION%.*}.x"
          bactopia --help_all --condadir ${GITHUB_WORKSPACE}/envs
          ls ${GITHUB_WORKSPACE}/tools | xargs -I {} bactopia tools {} --condadir ${GITHUB_WORKSPACE}/envs/tools-{}-{BACTOPIA_VERSION} --help
